image: node:latest

before_script:
    - export MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.4.1.tgz
    - export MONGOMS_VERSION=4.4.1

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - docker ps -a -q -f status=exited | xargs --no-run-if-empty docker rm -v
        - docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi
        - docker images | awk '/ago/  { print $3}' | xargs --no-run-if-empty docker rmi
        - docker volume ls -qf dangling=true | xargs --no-run-if-empty docker volume rm
        - yarn
    cache:
        - paths:
              - node_modules/
    artifacts:
        expire_in: 1 days
        when: on_success
        paths:
            - node_modules/

test:
    stage: test
    image: node:15-buster
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    dependencies:
        - build
    script:
        - yarn test:ci
    cache:
        - paths:
              - coverage/
    artifacts:
        paths:
            - coverage/
        when: always
        reports:
            junit:
                - junit.xml
            cobertura: coverage/cobertura-coverage.xml

pages:
    stage: deploy
    dependencies:
        - test
    script:
        - mkdir .public
        - cp -r coverage/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - dev
