stages:
    - build
    - test
    - deploy

before_script:
    - export MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.4.1.tgz
    - export MONGOMS_VERSION=4.4.1

build:
    stage: build
    script:
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
        - ". ~/.nvm/nvm.sh"
        - nvm --version
        - nvm install --lts
        - npm install --global yarn
        - df -h
        - yarn
    tags:
        - handwoong

test:
    stage: test
    image: node:15-buster
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    script:
        - yarn test:ci
    cache:
        - paths:
              - coverage/
    artifacts:
        paths:
            - coverage/
        when: always
        reports:
            junit:
                - junit.xml
            cobertura: coverage/cobertura-coverage.xml
    tags:
        - handwoong

pages:
    stage: deploy
    dependencies:
        - test
    script:
        - mkdir .public
        - cp -r coverage/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - dev
    tags:
        - handwoong
